-- ============================================================================
-- VoltHub CSMS — V007 grid control (FC-HCC, blueprint P.1 / ADR-0010)
-- Electrical hierarchy + control artifacts. Money path untouched: these tables
-- extend the store port (ADR-0005) and follow its invariants — append-only
-- control rows, status transitions instead of DELETE (the API role has none).
-- Error band: -2090x (GRID_CONTROL_*), mapped once in apps/api/src/errors.js.
-- ============================================================================

-- ---- electrical hierarchy ---------------------------------------------------
-- Adjacency tree: SITE -> PANEL -> FEEDER. cap monotonicity toward the root is
-- enforced by trg_grid_cap_monotonic (child cap <= parent cap) so a compiled
-- schedule can never violate a parent limit by construction.
CREATE TABLE grid_asset (
  asset_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  station_id    NUMBER NOT NULL,
  parent_id     NUMBER REFERENCES grid_asset(asset_id),
  kind          VARCHAR2(10) NOT NULL CHECK (kind IN ('SITE','PANEL','FEEDER')),
  label         VARCHAR2(120) NOT NULL,
  cap_kw        NUMBER(10,3) NOT NULL CHECK (cap_kw > 0),
  ramp_kw       NUMBER(10,3),              -- max interval-over-interval change
  status        VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','PENDING','RETIRED')),
  -- two-person rule (blueprint N.1): cap REDUCTIONS start PENDING and need a
  -- second, distinct ADMIN approval; proposed_by/approved_by record the chain.
  proposed_by   NUMBER,
  approved_by   NUMBER,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_grid_asset_station_label UNIQUE (station_id, label),
  CONSTRAINT fk_grid_asset_station FOREIGN KEY (station_id) REFERENCES station(station_id)
);
CREATE INDEX ix_grid_asset_station ON grid_asset (station_id, status);

-- Root must be exactly one SITE per station; parents must share the station.
CREATE OR REPLACE TRIGGER trg_grid_asset_shape
BEFORE INSERT OR UPDATE ON grid_asset FOR EACH ROW
DECLARE
  v_parent_station NUMBER;
  v_kind_count     NUMBER;
BEGIN
  IF :NEW.parent_id IS NOT NULL THEN
    SELECT station_id INTO v_parent_station FROM grid_asset WHERE asset_id = :NEW.parent_id;
    IF v_parent_station != :NEW.station_id THEN
      RAISE_APPLICATION_ERROR(-20902, 'GRID_CAP_MONOTONIC: parent asset belongs to a different station');
    END IF;
  END IF;
  IF :NEW.kind = 'SITE' AND :NEW.parent_id IS NOT NULL THEN
    RAISE_APPLICATION_ERROR(-20901, 'GRID_ASSET_INVALID: SITE is the root (no parent)');
  END IF;
  IF :NEW.kind IN ('PANEL','FEEDER') AND :NEW.parent_id IS NULL THEN
    RAISE_APPLICATION_ERROR(-20901, 'GRID_ASSET_INVALID: ' || :NEW.kind || ' requires a parent');
  END IF;
  IF :NEW.kind = 'SITE' THEN
    SELECT COUNT(*) INTO v_kind_count FROM grid_asset
      WHERE station_id = :NEW.station_id AND kind = 'SITE' AND status != 'RETIRED'
        AND (:NEW.asset_id IS NULL OR asset_id != :NEW.asset_id);
    IF v_kind_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20901, 'GRID_ASSET_INVALID: station already has a SITE root');
    END IF;
  END IF;
END;
/

-- Cap monotonicity toward the root (blueprint P.1: "PL/SQL validation of cap
-- monotonicity toward root"). A child may never promise more than its parent.
CREATE OR REPLACE TRIGGER trg_grid_cap_monotonic
BEFORE INSERT OR UPDATE OF cap_kw, parent_id ON grid_asset FOR EACH ROW
DECLARE
  v_parent_cap NUMBER;
BEGIN
  IF :NEW.parent_id IS NOT NULL THEN
    SELECT cap_kw INTO v_parent_cap FROM grid_asset WHERE asset_id = :NEW.parent_id;
    IF :NEW.cap_kw > v_parent_cap THEN
      RAISE_APPLICATION_ERROR(-20902,
        'GRID_CAP_MONOTONIC: child cap ' || :NEW.cap_kw || ' kW exceeds parent cap ' || v_parent_cap || ' kW');
    END IF;
  END IF;
END;
/

-- ---- control decisions (append-only, one optimizer run) ---------------------
CREATE TABLE control_decision (
  decision_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  site_id        NUMBER NOT NULL REFERENCES station(station_id),
  horizon_start  TIMESTAMP NOT NULL,
  interval_min   NUMBER(3) DEFAULT 15 NOT NULL,
  payload_json   CLOB NOT NULL,             -- full x[v][t] schedule + unmet report
  bounds_hash    VARCHAR2(64) NOT NULL,     -- forecast/quantile provenance (blueprint L.1)
  solver         VARCHAR2(40) NOT NULL,     -- 'fchcc-lp-merit' | 'fchcc-sidecar-highs' | ...
  runtime_ms     NUMBER(10,2),
  state_version  NUMBER,                    -- staleness guard input (blueprint O.2)
  status         VARCHAR2(12) DEFAULT 'COMMITTED' NOT NULL CHECK (status IN ('COMMITTED','SUPERSEDED','FAILED')),
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_control_decision_site ON control_decision (site_id, decision_id DESC);

-- ---- per-vehicle feasibility certificates -----------------------------------
CREATE TABLE feasibility_certificate (
  cert_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  session_id      NUMBER REFERENCES charging_session(session_id),
  reservation_id  NUMBER REFERENCES reservation(reservation_id),
  station_id      NUMBER NOT NULL REFERENCES station(station_id),
  cp_id           NUMBER NOT NULL,
  connector_no    NUMBER NOT NULL,
  floor_kw        NUMBER(10,3) NOT NULL CHECK (floor_kw >= 0),   -- guaranteed power while ACTIVE
  margin_kwh      NUMBER(10,3) NOT NULL CHECK (margin_kwh >= 0), -- worst-case slack at admission
  worst_case_kwh  NUMBER(10,3) NOT NULL,                          -- deliverable under worst case
  required_kwh    NUMBER(10,3) NOT NULL,
  deadline_at     TIMESTAMP NOT NULL,
  decision_id     NUMBER REFERENCES control_decision(decision_id),
  status          VARCHAR2(10) DEFAULT 'ISSUED' NOT NULL
                  CHECK (status IN ('ISSUED','ACTIVE','ERODED','FAILED','MET')),
  issued_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  reason          VARCHAR2(200),
  CONSTRAINT ck_cert_target CHECK (
    (session_id IS NOT NULL AND reservation_id IS NULL) OR
    (session_id IS NULL AND reservation_id IS NOT NULL))
);
CREATE INDEX ix_cert_session ON feasibility_certificate (session_id, status);
CREATE INDEX ix_cert_station ON feasibility_certificate (station_id, status);

-- ---- protocol artifact audit (decision -> OCPP message binding) -------------
CREATE TABLE charging_profile_push (
  push_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  decision_id     NUMBER NOT NULL REFERENCES control_decision(decision_id),
  cp_id           NUMBER NOT NULL REFERENCES charge_point(cp_id),
  profile_payload CLOB NOT NULL,
  payload_sha256  VARCHAR2(64) NOT NULL,
  clamped         CHAR(1) DEFAULT 'N' NOT NULL CHECK (clamped IN ('Y','N')),
  push_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ack_result      VARCHAR2(20),               -- Accepted | Rejected | TIMEOUT
  CONSTRAINT uq_push_cp_decision UNIQUE (cp_id, decision_id)   -- idempotent per (cp, decision)
);

-- ---- dead letters (poison events + rejected pushes; operator triage) --------
CREATE TABLE dead_letter (
  letter_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  event_ref     VARCHAR2(200) NOT NULL,       -- dedupe_key / push_id / event_id
  kind          VARCHAR2(40) NOT NULL,
  reason_code   VARCHAR2(40) NOT NULL,
  detail        VARCHAR2(500),
  payload       CLOB,
  first_seen_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  last_seen_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status        VARCHAR2(10) DEFAULT 'OPEN' NOT NULL CHECK (status IN ('OPEN','REPLAYED','DISMISSED')),
  CONSTRAINT uq_dead_letter_ref UNIQUE (event_ref)
);
CREATE INDEX ix_dead_letter_status ON dead_letter (status, first_seen_at);

-- ---- append-only discipline: no DELETE anywhere (house rule, V004) ---------
CREATE OR REPLACE TRIGGER trg_grid_control_no_delete
BEFORE DELETE ON control_decision FOR EACH ROW
BEGIN RAISE_APPLICATION_ERROR(-20901, 'GRID_ASSET_INVALID: control_decision is append-only'); END;
/
CREATE OR REPLACE TRIGGER trg_cert_no_delete
BEFORE DELETE ON feasibility_certificate FOR EACH ROW
BEGIN RAISE_APPLICATION_ERROR(-20901, 'GRID_ASSET_INVALID: feasibility_certificate is append-only'); END;
/
CREATE OR REPLACE TRIGGER trg_push_no_delete
BEFORE DELETE ON charging_profile_push FOR EACH ROW
BEGIN RAISE_APPLICATION_ERROR(-20901, 'GRID_ASSET_INVALID: charging_profile_push is append-only'); END;
/
