// OpenAPI 3.0 spec for /api/v1/docs (hand-maintained, mirrors routes.js).
// Replaces codegen: every path below is implemented + covered by tests.
'use strict';
const spec = {
  openapi: '3.0.3',
  info: { title: 'VoltHub CSMS API', version: '1.0.0', description: 'Two-engine EV charging management. Oracle error bands (-205xx..-208xx) map to HTTP in `error.ora`.' },
  servers: [{ url: '/api/v1' }],
  components: {
    securitySchemes: { bearer: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
    schemas: {
      Error: { type: 'object', properties: { error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' }, ora: { type: 'integer', nullable: true }, requestId: { type: 'string' } } } } },
    },
  },
  security: [{ bearer: [] }],
  paths: {},
};
const P = (summary, extra = {}) => ({ ...extra, summary, responses: { 200: { description: 'ok' }, '4xx': { description: 'client error' } } });
Object.assign(spec.paths, {
  '/health': { get: P('Liveness + mode/outbox lag (see /health/deep for engine probes)', { security: [] }) },
  '/health/deep': { get: P('Deep probes: SELECT 1 FROM DUAL + pool + Timescale reachability', { security: [] }) },
  '/metrics': { get: P('Prometheus text: req rate, p95 ring, outbox depth, pool, OCPP, sessions', { security: [] }) },
  '/docs': { get: P('This OpenAPI document', { security: [] }) },
  '/auth/register': { post: P('Driver register (welcome ₹500 credit)', { security: [] }) },
  '/auth/login': { post: P('Login → 15-min JWT + rotating refresh', { security: [] }) },
  '/auth/refresh': { post: P('Rotate refresh token (family revocation on reuse)') },
  '/me': { get: P('Profile + wallet') },
  '/me/wallet/topup': { post: P('Prepaid top-up (append-only ledger)') },
  '/me/vehicles': { get: P('My EVs'), post: P('Register EV (battery 5..250 kWh)') },
  '/me/vehicles/{id}': { patch: P('Rename / set default EV') },
  '/me/notifications': { get: P('In-app events (reservation/session/invoice)') },
  '/me/notifications/{id}/read': { post: P('Mark notification read') },
  '/stations': { get: P('Search: q/std/minKw/lat/lng/radius/page (RSC, 15s revalidate)', { security: [] }) },
  '/stations/{id}': { get: P('Detail: charge points, live connectors, amenities, rating', { security: [] }) },
  '/stations/{id}/connectors/live': { get: P('Live connector feed (15s poll)', { security: [] }) },
  '/stations/{id}/sessions/active': { get: P('Active sessions on this station (auth: driver sees own scope, staff scoped)') },
  '/stations/{id}/analytics': { get: P('Revenue/energy/util/active/faults (operator)') },
  '/stations/{id}/faults': { post: P('Manual fault report (connector → FAULTED)') },
  '/stations/{id}/reviews': { get: P('Station reviews', { security: [] }) },
  '/tariffs/active': { get: P('Current tariff versions + ToU bands (public preview)', { security: [] }) },
  '/reservations': { get: P('My bookings (driver) / all (staff)'), post: P('Reserve 15–120 min. 409 OVERLAP / NOT_BOOKABLE, Idempotency-Key replay') },
  '/reservations/{id}/cancel': { post: P('Optimistic cancel pre-start') },
  '/sessions/start': { post: P('Plug-in: RESERVED→PREPARING (converts reservation)') },
  '/sessions': { get: P('History, keyset cursor pagination') },
  '/sessions/active/{ref}': { get: P('Active session on connector (auth required)') },
  '/sessions/{id}/live': { get: P('Live kWh/kW/elapsed/est-cost + 60-pt trace, 5s poll (auth: owner or staff)') },
  '/sessions/{id}/state': { patch: P('Operator transition: SUSPENDED↔CHARGING (matrix-enforced)') },
  '/sessions/{id}/remote-stop': { post: P('Remote stop → COMPLETED') },
  '/sessions/{id}/bill': { post: P('Bill exactly once → DUE invoice (409 if already billed)') },
  '/sessions/{id}/review': { post: P('One 1–5 review per session') },
  '/invoices': { get: P('Due worklist + history') },
  '/invoices/{id}': { get: P('Invoice + itemized lines + payments') },
  '/invoices/{id}/pay': { post: P('Wallet pay. 402 INSUFFICIENT_FUNDS, 409 if not DUE') },
  '/faults': { get: P('Fault queue (?open=1, ?station=)') },
  '/faults/{id}/maintenance': { post: P('Open maintenance record (operator)') },
  '/maintenance/{id}/complete': { patch: P('Resolve → connector back to AVAILABLE') },
  '/telemetry/load-curve': { get: P('Gap-filled load curve (?station&from&to&bucket). Timescale cagg when TS_HOST set, else local rollup (auth required)') },
  '/telemetry/utilization-heatmap': { get: P('7×24 utilization matrix (auth required)') },
  '/admin/users': { post: P('Create operator (admin)') },
  '/admin/users/{id}': { patch: P('Suspend / assign station (admin)') },
  '/admin/stations': { get: P('All stations incl. inactive (staff)'), post: P('Create station + charge points + connectors (admin)') },
  '/admin/stations/{id}': { patch: P('Activate/deactivate, reassign operator (admin)') },
  '/admin/charge-points': { post: P('Provision charge point → OCPP identity (admin)') },
  '/admin/tariff-plans': { get: P('Version timeline (staff)'), post: P('New immutable version, supersedes active (admin)') },
  '/admin/audit-logs': { get: P('Mutation trail with old/new JSON (admin)') },
});
module.exports = spec;
